# spring-cloud-upms-server 配置文件
info:
    name: 内容管理系统
    description: 服务 - CMS 内容管理系统 - 服务提供者
server:
  port: 9100

---
spring:
  profiles: dev
# actuator 端点取消安全限制，通过 /application/endpoint 直接访问
# 参考地址：https://docs.spring.io/spring-boot/docs/2.0.0.M3/reference/htmlsingle/#production-ready-sensitive-endpoints
management:
  security:
    enabled: false
